"""miner url

Revision ID: 7012af2f8da4
Revises: 5c32e91ec9ea
Create Date: 2024-10-02 18:27:00.635244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7012af2f8da4'
down_revision: Union[str, None] = '5c32e91ec9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_miner_active_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_miner_active_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_validator_active_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_validator_active_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_miner_history_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_miner_history_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_validator_history_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_validator_history_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_main_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miner_unique_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('hotkey', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('date_started', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('date_approved', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('campaign', sa.Column('store_name', sa.String(), nullable=True))
    op.add_column('campaign', sa.Column('validator_id', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('country_of_registration', sa.String(), nullable=True))
    op.add_column('campaign', sa.Column('company_registration_number', sa.String(), nullable=True))
    op.add_column('campaign', sa.Column('countries_approved_for_product_sales', sa.String(), nullable=True))
    op.add_column('campaign', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_main_engine() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'updated_at')
    op.drop_column('campaign', 'countries_approved_for_product_sales')
    op.drop_column('campaign', 'company_registration_number')
    op.drop_column('campaign', 'country_of_registration')
    op.drop_column('campaign', 'validator_id')
    op.drop_column('campaign', 'store_name')
    op.drop_column('campaign', 'product_name')
    op.drop_column('campaign', 'date_approved')
    op.drop_column('campaign', 'date_started')
    op.drop_column('campaign', 'created_at')
    op.drop_table('miner_unique_link')
    # ### end Alembic commands ###

